### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-css-font-families#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://ravedave.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/css-font-families/1) criteria:
- [x] include at least one font from Google Fonts in your page, using a `link` element
- [x] include at least one font from DaFont.com in your page, using a `@font-face` rule
- [x] every included font should be visibly applied to text on the page

**Comment by chrisvfritz** [comment]
Looks great! I especially enjoyed the added `text-shadow` effect you included. :smiley: :tada: :shipit:
